<a href="https://colab.research.google.com/github/SumanthSrikanta/DeepLearning/blob/master/TensorIndexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
tensor_indexed = tf.constant([3, 6, 4, 22, 10, 2, 34])
print(tensor_indexed)

tf.Tensor([ 3  6  4 22 10  2 34], shape=(7,), dtype=int32)


In [4]:
print(tensor_indexed[0:4])

tf.Tensor([ 3  6  4 22], shape=(4,), dtype=int32)


In [8]:
print(tensor_indexed[1:5+1])
#+1 is similar to range

tf.Tensor([ 6  4 22 10  2], shape=(5,), dtype=int32)


In [11]:
tf.range(2,5+1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [12]:
print(tensor_indexed[1:6:2])

tf.Tensor([ 6 22  2], shape=(3,), dtype=int32)


In [14]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-7],
    [4,6,-1]
])
print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [4 6]], shape=(3, 2), dtype=int32)


In [18]:
print(tensor_two_d[0:2, ])
#row and then column

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -7]], shape=(2, 3), dtype=int32)


In [17]:
print(tensor_two_d[2:3,])

tf.Tensor([[ 4  6 -1]], shape=(1, 3), dtype=int32)


In [19]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [-5,2,0]],
    [[2,10,-43],
     [4,-1,0]],
    [[3,23,-9],
     [3,5,87]
    ]
])
print(tensor_three_d[0:1,1:,])

tf.Tensor([[[-5  2  0]]], shape=(1, 1, 3), dtype=int32)
