<a href="https://colab.research.google.com/github/SumanthSrikanta/DeepLearning/blob/master/TensorMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [4]:
fill_tensor = tf.fill(
    [3,4,3], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5]
  [5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]
  [5 5 5]]], shape=(3, 4, 3), dtype=int32)


In [6]:
tensor_ones = tf.ones(
    [3,4],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(tensor_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [7]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(3, 4, 3), dtype=int32)


In [8]:
zero_tensors =tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(zero_tensors)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [9]:
print(tf.shape(zero_tensors))

tf.Tensor([3 2], shape=(2,), dtype=int32)


In [10]:
print(tf.rank(zero_tensors))

tf.Tensor(2, shape=(), dtype=int32)


In [17]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.rank(t)
#rank is dimension of tensor

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [18]:
tf.size(t)
#size is number of characters in a tensor

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [22]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.69861   99.814064]
 [100.24798  100.925224]
 [100.933655  98.42595 ]], shape=(3, 2), dtype=float32)


In [31]:
random_uniform = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_uniform)

tf.Tensor(
[[575 622 797 673 294]
 [108 449 371 828 876]
 [ 78 888 731  97 446]
 [830 799 292 162 175]
 [132 635   9 732 996]], shape=(5, 5), dtype=int32)
