<a href="https://colab.research.google.com/github/SumanthSrikanta/DeepLearning/blob/master/TensorDimensionsAndDatatypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [9]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [13]:
tensor_three_d = tf.constant([

    [[1,2,3],
     [2,0,-1]],

    [[1,5,-9],
     [1,4,6]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 2  0 -1]]

 [[ 1  5 -9]
  [ 1  4  6]]], shape=(2, 2, 3), dtype=int32)


In [14]:
print(tensor_three_d.shape)

(2, 2, 3)


In [15]:
tensor_three_d.ndim

3

In [16]:
tensor_four_d = tf.constant([

   [ [[1,2,3],
     [2,0,-1]],

    [[1,5,-9],
     [1,4,6]] ],
   [ [[1,2,3],
     [2,0,-1]],

    [[1,5,-9],
     [1,4,6]]

    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3]
   [ 2  0 -1]]

  [[ 1  5 -9]
   [ 1  4  6]]]


 [[[ 1  2  3]
   [ 2  0 -1]]

  [[ 1  5 -9]
   [ 1  4  6]]]], shape=(2, 2, 2, 3), dtype=int32)


In [19]:
tensor_one_d = tf.constant([2,0,-8,23], dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([ 2.  0. -8. 23.], shape=(4,), dtype=float16)


In [24]:
tensor_error = tf.constant([2,0.2,3], dtype=tf.float64)

casted_tensor = tf.cast(tensor_error, dtype=tf.int64)
print(tensor_error)
print(casted_tensor)

tf.Tensor([2.  0.2 3. ], shape=(3,), dtype=float64)
tf.Tensor([2 0 3], shape=(3,), dtype=int64)


In [25]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [26]:
tensor_string = tf.constant("Hello World")
print(tensor_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [28]:
tensor_string = tf.constant(["Hello","Hi"])
print(tensor_string)

tf.Tensor([b'Hello' b'Hi'], shape=(2,), dtype=string)


In [1]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [4]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [6]:
eye_tensor = tf.eye(
    num_rows= 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)
print(3* eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [7]:
eye_tensor = tf.eye(
    num_rows= 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)
